server:
  port: 8081

spring:
  datasource:
    # Adding the timezone force to the URL string
    url: jdbc:postgresql://localhost:5432/food_auth_db?options=-c%20timezone=UTC
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # This tells Hibernate to stop trying to guess the dialect from the connection
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC